function data()
return {
	en = {

		["mod_name"] = "Electric Mobility",
		["mod_desc"] = "This package contains assets for electromobility. These include charging stations, charging parks, ground markings for car parks and signs. All assets have additional options. Available from 2003.",
		["name_ladepark"] = "E-Mobility",
		["desc_ladepark"] = "Different assets for electric cars.",
		["type"] = "Electric Mobility Assets",
		["extensions"] = "\n- Configuration Charging Park -\n\nExtensions",
		["reflection"] = "Mirror",
		["roof"] = "Glass roof",
		["charger"] = "2nd Charging column",
		["style"] = "Design",
		["classic"] = "classic",
		["modern"] = "modern",
		["terrain"] = "TRerrain alignment",
		["ground"] = "\n\n- Configuration ground markings -\n\nversion",
		["symbol"] = "Symbol",
		["outline"] = "Outline",
		["chargerType"] = "\n\n- Configuration Charger -\n\ncharger type",
		["supercharger"] = "supercharger",
		["Ladestation"] = "Ladesäule",
		["mainSigns"] = "\n\n- Configuration Signs -\n\nmain sign",
		["extraSigns"] = "additional sign",
		["etankstelle"] = "Carger",
		["parkplatz"] = "Parking",
		["eauto"] = "Electric car",
		["fahrzeuge"] = "Electric vehicles",

	},
	de = {

		["mod_name"] = "Elektromobilität",
		["mod_desc"] = "Dieses Paket enthält Assets für die Elektromobilität. Dazu zählen Ladesäulen, Ladeparks, Bodenmarkierungen für Parkplätze und Schilder. Alle Assets haben noch zusätzliche Optionen. Verfügbar ab 2003.",
		["name_ladepark"] = "E-Mobilität",
		["desc_ladepark"] = "Verschiedene Assets für E-Autos.",
		["type"] = "Elektromobilität Assets",
		["extensions"] = "\n- Optionen Ladepark -\n\nErweiterungen",
		["reflection"] = "Spiegelung",
		["roof"] = "Glasdach",
		["charger"] = "2. Ladesäule",
		["style"] = "Design",
		["classic"] = "klassisch",
		["modern"] = "modern",
		["terrain"] = "Terrain angleichen",
		["ground"] = "\n\n- Optionen Bodenmarkierung -\n\nVariante",
		["symbol"] = "Symbol",
		["outline"] = "Parkplatz",
		["chargerType"] = "\n\n- Option Charger -\n\nCharger Typ",
		["supercharger"] = "Supercharger",
		["Ladestation"] = "Ladesäule",
		["mainSigns"] = "\n\n- Optionen Schilder -\n\nHauptschild",
		["extraSigns"] = "Zusatzschild",
		["etankstelle"] = "E-Tankstelle",
		["parkplatz"] = "Parkplatz",
		["eauto"] = "E-Auto",
		["fahrzeuge"] = "Elektrofahrzeuge",

	},
}
end
