function data()
return {
	en = {
		["mod_name"] = "Electric Mobility",
		["mod_desc"] = "",
		["name_ladepark"] = "EnBW Charging Park",
		["desc_ladepark"] = "Asset for electric car.",
		["type"] = "Electric Mobility Assets",
		["extensions"] = "\n- Configuration Charging Park -\n\nExtenstions",
		["reflection"] = "Mirror",
		["roof"] = "Glass roof",
		["charger"] = "2. Charging column",
		["style"] = "Design",
		["classic"] = "classic",
		["modern"] = "modern",
		["terrain"] = "terrain alignment",
		["ground"] = "\n\n- Configuration ground markings -\n\nversion",
		["symbol"] = "symbol",
		["outline"] = "outline",
		["mainSigns"] = "\n\n- Configuration Signs -\n\nmain sign",
		["extraSigns"] = "extra sign",
		["etankstelle"] = "carger",
		["parkplatz"] = "parking",
		["eauto"] = "electric car",
		["fahrzeuge"] = "electric vehicles",
	},
	de = {
		["mod_name"] = "Elektromobilität",
		["mod_desc"] = "",
		["name_ladepark"] = "EnBW Ladepark",
		["desc_ladepark"] = "Ein Asset für E-Autos.",
		["type"] = "Elektromobilität Assets",
		["extensions"] = "\n- Optionen Ladepark -\n\nErweiterungen",
		["reflection"] = "Spiegelung",
		["roof"] = "Glasdach",
		["charger"] = "2. Ladesäule",
		["style"] = "Design",
		["classic"] = "klassisch",
		["modern"] = "modern",
		["terrain"] = "Terrain angleichen",
		["ground"] = "\n\n- Optionen Bodenmarkierung -\n\nVariante",
		["symbol"] = "Symbol",
		["outline"] = "Parkplatz",
		["mainSigns"] = "\n\n- Optionen Schilder -\n\nHauptschild",
		["extraSigns"] = "Zusatzschild",
		["etankstelle"] = "E-Tankstelle",
		["parkplatz"] = "Parkplatz",
		["eauto"] = "E-Auto",
		["fahrzeuge"] = "Elektrofahrzeuge",
	},
}
end
